kernelsu-objs := core/init.o

kernelsu-objs += feature/kernel_umount.o
kernelsu-objs += feature/sulog.o
kernelsu-objs += feature/seccomp_hook.o
ifeq ($(CONFIG_KSU_SUSFS),y)
kernelsu-objs += feature/sucompat_susfs.o
else
kernelsu-objs += feature/sucompat.o
kernelsu-objs += feature/hook_status.o
endif

kernelsu-objs += hook/lsm_hook.o
ifeq ($(CONFIG_KSU_SUSFS),y)
kernelsu-objs += hook/setuid_hook_susfs.o
kernelsu-objs += hook/arm64/patch_memory.o
else
kernelsu-objs += hook/setuid_hook.o
kernelsu-objs += hook/syscall_event_bridge.o
kernelsu-objs += hook/syscall_hook_manager.o
kernelsu-objs += hook/tp_marker.o
ifeq ($(CONFIG_ARM64),y)
kernelsu-objs += hook/arm64/patch_memory.o
kernelsu-objs += hook/arm64/syscall_hook.o
else ifeq ($(CONFIG_X86_64),y)
kernelsu-objs += hook/x86_64/patch_memory.o
kernelsu-objs += hook/x86_64/syscall_hook.o
else ifeq ($(CONFIG_RISCV),y)
kernelsu-objs += hook/riscv64/patch_memory.o
kernelsu-objs += hook/riscv64/syscall_hook.o
endif
endif

kernelsu-objs += infra/file_wrapper.o
kernelsu-objs += infra/event_queue.o
kernelsu-objs += infra/seccomp_cache.o
kernelsu-objs += infra/su_mount_ns.o
kernelsu-objs += infra/symbol_resolver.o

ifneq ($(CONFIG_KSU_DISABLE_MANAGER),y)
kernelsu-objs += feature/dynamic_manager.o
kernelsu-objs += manager/apk_sign.o
kernelsu-objs += manager/manager.o
kernelsu-objs += manager/pkg_observer.o
kernelsu-objs += manager/throne_tracker.o
endif

kernelsu-objs += policy/allowlist.o
kernelsu-objs += policy/app_profile.o
kernelsu-objs += policy/feature.o

kernelsu-objs += runtime/boot_event.o
ifeq ($(CONFIG_KSU_SUSFS),y)
kernelsu-objs += runtime/ksud_integration_susfs.o
else
kernelsu-objs += runtime/ksud_integration.o
endif

kernelsu-objs += selinux/selinux.o
kernelsu-objs += selinux/rules.o
kernelsu-objs += selinux/sepolicy.o

ifeq ($(CONFIG_KSU_SUSFS),y)
kernelsu-objs += sulog/event_susfs.o
else
kernelsu-objs += sulog/event.o
endif
kernelsu-objs += sulog/fd.o

kernelsu-objs += supercall/dispatch.o
kernelsu-objs += supercall/perm.o
kernelsu-objs += supercall/supercall.o

ifeq ($(CONFIG_KSU_SUSFS),y)
kernelsu-objs += feature/adb_root_susfs.o
else
kernelsu-objs += feature/adb_root.o
endif

ifeq ($(CONFIG_KSU_SUSFS),y)
kernelsu-objs += feature/selinux_hide_susfs.o
else
kernelsu-objs += feature/selinux_hide.o
kernelsu-objs += feature/avc_spoof.o
endif

ifeq ($(CONFIG_ABK_CONTROL),)
ifneq ($(filter y m,$(CONFIG_KSU)),)
CONFIG_ABK_CONTROL := $(CONFIG_KSU)
endif
endif

ifneq ($(filter y m,$(CONFIG_ABK_CONTROL)),)
kernelsu-objs += abk_control/core.o
kernelsu-objs += abk_control/manifest.o
endif

ifeq ($(CONFIG_KPM),y)
ifneq ($(CONFIG_KSU),y)
$(error CONFIG_KPM requires built-in CONFIG_KSU=y)
endif
ifneq ($(CONFIG_ARM64),y)
$(error CONFIG_KPM requires CONFIG_ARM64=y)
endif
# Native KPM is a built-in GKI ABI bridge. It must never be linked into the
# LKM variant, whose KPM backend requires an independently installed KPatch-Next.
kernelsu-objs += kpm/kpm.o
kernelsu-objs += kpm/compact.o
kernelsu-objs += kpm/super_access.o
endif

ifdef KBUILD_EXTMOD
ifeq ($(CONFIG_KSU_DISABLE_MANAGER),y)
ccflags-y += -DCONFIG_KSU_DISABLE_MANAGER=1
endif
ifeq ($(CONFIG_KSU_DISABLE_POLICY),y)
ccflags-y += -DCONFIG_KSU_DISABLE_POLICY=1
endif
ifeq ($(CONFIG_KSU_DEBUG),y)
ccflags-y += -DCONFIG_KSU_DEBUG=1
endif
ifeq ($(CONFIG_KSU_X86_PATCH_SYSCALL_DISPATCHER),y)
ccflags-y += -DCONFIG_KSU_X86_PATCH_SYSCALL_DISPATCHER=1
endif
endif

ccflags-y += -I$(srctree)/security/selinux -I$(srctree)/security/selinux/include
ccflags-y += -I$(objtree)/security/selinux -include $(srctree)/include/uapi/asm-generic/errno.h

ifneq ($(KBUILD_EXTMOD),)
# 6.18 exports the external module source as srcroot when M/MO are used.
ifneq ($(srcroot),)
KSU_KERNEL_DIR := $(srcroot)
endif
endif
ifndef KSU_KERNEL_DIR
KSU_SRC_REAL := $(realpath $(src))
ifneq ($(KSU_SRC_REAL),)
KSU_KERNEL_DIR := $(KSU_SRC_REAL)
else
ifeq ($(filter /%,$(src)),)
KSU_KERNEL_DIR := $(srctree)/$(src)
else
KSU_KERNEL_DIR := $(src)
endif
endif
endif
KSU_KERNEL_DIR := $(abspath $(KSU_KERNEL_DIR))
KSU_KERNEL_DIR_REAL := $(realpath $(KSU_KERNEL_DIR))
ifneq ($(KSU_KERNEL_DIR_REAL),)
KSU_KERNEL_DIR := $(KSU_KERNEL_DIR_REAL)
endif
KSU_ROOT_DIR := $(abspath $(KSU_KERNEL_DIR)/..)

ccflags-y += -I$(KSU_KERNEL_DIR) -I$(KSU_KERNEL_DIR)/include -I$(KSU_ROOT_DIR)
ccflags-y += -I$(objtree)/security/selinux/include

obj-$(CONFIG_KSU) += kernelsu.o

MDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
KSU_VERSION_FILE := $(abspath $(MDIR)/../version.properties)
KSU_FALLBACK_VERSION := $(shell sed -n 's/^versionCode=//p' $(KSU_VERSION_FILE) 2>/dev/null | head -n 1)
KSU_VERSION_OVERRIDE := $(strip $(KSU_VERSION_OVERRIDE))

# Workaround bazel
# https://github.com/tiann/KernelSU/pull/316#issuecomment-1479043219
GIT := $(shell PATH="$$PATH":/usr/bin:/usr/local/bin which git)
ifneq ($(GIT),)
# Check if this is a git repository
# Try to detect Git repo intelligently
GIT_ROOT := $(shell cd $(MDIR) && $(GIT) rev-parse --show-toplevel 2>/dev/null)
ifneq ($(GIT_ROOT),)
KERNEL_GIT_ROOT := $(shell cd $(srctree) && $(GIT) rev-parse --show-toplevel 2>/dev/null)
ifneq ($(GIT_ROOT),$(KERNEL_GIT_ROOT))
# Only set version if it's a different repo from kernel
$(shell cd $(GIT_ROOT) && [ -f .git/shallow ] && $(GIT) fetch --unshallow 2>/dev/null || true)
KSU_GIT_VERSION := $(shell cd $(GIT_ROOT) && $(GIT) rev-list --count HEAD 2>/dev/null)
KSU_GIT_VERSION_VALID := 1
$(info -- KernelSU: Git repo detected at $(GIT_ROOT))
endif
endif
else
$(warning -- KernelSU: Git not detected, make sure git is installed in your PATH!)
endif


ifneq ($(KSU_VERSION_OVERRIDE),)
$(info -- KernelSU version: $(KSU_VERSION_OVERRIDE) from KSU_VERSION_OVERRIDE)
ccflags-y += -DKSU_VERSION=$(KSU_VERSION_OVERRIDE)
else
ifneq ($(KSU_FALLBACK_VERSION),)
$(info -- KernelSU version: $(KSU_FALLBACK_VERSION) from $(KSU_VERSION_FILE))
ccflags-y += -DKSU_VERSION=$(KSU_FALLBACK_VERSION)
else
# Calculate version if git version is available
ifdef KSU_GIT_VERSION_VALID
# ksu_version: major * 10000 + git version + 200 for historical reasons
$(eval KSU_VERSION=$(shell expr 30000 + $(KSU_GIT_VERSION)))
$(info -- KernelSU version: $(KSU_VERSION))
ccflags-y += -DKSU_VERSION=$(KSU_VERSION)
else
$(warning "KSU_GIT_VERSION not defined! It is better to make KernelSU a git repository!")
ccflags-y += -DKSU_VERSION=16
endif
endif
endif

KSU_NEW_DCACHE_FLUSH := $(shell grep -q __flush_dcache_area $(srctree)/arch/arm64/include/asm/cacheflush.h ; echo $$?)
$(info -- KSU_NEW_DCACHE_FLUSH: $(KSU_NEW_DCACHE_FLUSH))

KSU_MANAGER_IDENTITY ?= $(abspath $(MDIR)/../dist/manager_identity.mk)
ifneq ($(wildcard $(KSU_MANAGER_IDENTITY)),)
include $(KSU_MANAGER_IDENTITY)
$(info -- KernelSU Manager identity: $(KSU_MANAGER_IDENTITY))
endif

ifndef KSU_MANAGER_PACKAGE
KSU_MANAGER_PACKAGE := io.github.fixz.stersu
endif

ifndef KSU_MANAGER_PACKAGE_LEGACY
KSU_MANAGER_PACKAGE_LEGACY := io.github.fixz.apkesu
endif

ifndef KSU_EXPECTED_SIZE
KSU_EXPECTED_SIZE := 0x02e8
endif

ifndef KSU_EXPECTED_HASH
KSU_EXPECTED_HASH := 1c89980c03432844cfe195dab90bfaecbcd987d19309da648014164be78007d1
endif

KSU_IS_PR_BUILD ?= 0
ifeq ($(KSU_IS_PR_BUILD),0)
KSU_PACKAGE_NAME ?= $(KSU_MANAGER_PACKAGE)
else
KSU_PACKAGE_NAME ?= $(KSU_MANAGER_PACKAGE).dev
endif

ccflags-y += -DKSU_MANAGER_PACKAGE=\"$(KSU_MANAGER_PACKAGE)\"
ifdef KSU_MANAGER_PACKAGE_LEGACY
ccflags-y += -DKSU_MANAGER_PACKAGE_LEGACY=\"$(KSU_MANAGER_PACKAGE_LEGACY)\"
$(info -- KernelSU legacy Manager package name: $(KSU_MANAGER_PACKAGE_LEGACY))
endif

$(info -- KernelSU Manager package name: $(KSU_PACKAGE_NAME))
$(info -- KernelSU Manager signature size: $(KSU_EXPECTED_SIZE))
$(info -- KernelSU Manager signature hash: $(KSU_EXPECTED_HASH))
$(info -- KernelSU is PR Build: $(KSU_IS_PR_BUILD))

ccflags-y += -DKSU_PACKAGE_NAME=\"$(KSU_PACKAGE_NAME)\"
ccflags-y += -DEXPECTED_SIZE=$(KSU_EXPECTED_SIZE)
ccflags-y += -DEXPECTED_HASH=\"$(KSU_EXPECTED_HASH)\"
ccflags-y += -DKSU_IS_PR_BUILD=$(KSU_IS_PR_BUILD)

ifdef KSU_EXPECTED_SIZE2
ifndef KSU_EXPECTED_HASH2
$(error KSU_EXPECTED_HASH2 must be set when KSU_EXPECTED_SIZE2 is set)
endif
ccflags-y += -DEXPECTED_SIZE2=$(KSU_EXPECTED_SIZE2)
ccflags-y += -DEXPECTED_HASH2=\"$(KSU_EXPECTED_HASH2)\"
$(info -- KernelSU Manager signature size2: $(KSU_EXPECTED_SIZE2))
$(info -- KernelSU Manager signature hash2: $(KSU_EXPECTED_HASH2))
endif

ccflags-y += -DKSU_NEW_DCACHE_FLUSH=$(KSU_NEW_DCACHE_FLUSH)

ifneq ($(filter y m,$(CONFIG_ABK_CONTROL)),)
ifndef ABK_MANAGER_PACKAGE
ABK_MANAGER_PACKAGE := com.abk.kernel
endif
ifndef ABK_MANAGER_CERT_SIZE
ABK_MANAGER_CERT_SIZE := 1407
endif
ifndef ABK_MANAGER_CERT_SHA256
ABK_MANAGER_CERT_SHA256 := 34e5e843952277759603cd0f949770b24c868530d80d7baeff08776a7e132b16
endif
ifndef ABK_MANAGER_CERT_MAX_LENGTH
ABK_MANAGER_CERT_MAX_LENGTH := 2048
endif

ccflags-y += -DABK_MANAGER_PACKAGE=\"$(ABK_MANAGER_PACKAGE)\"
ccflags-y += -DABK_MANAGER_CERT_SIZE=$(ABK_MANAGER_CERT_SIZE)
ccflags-y += -DABK_MANAGER_CERT_SHA256=\"$(ABK_MANAGER_CERT_SHA256)\"
ccflags-y += -DABK_MANAGER_CERT_MAX_LENGTH=$(ABK_MANAGER_CERT_MAX_LENGTH)
ccflags-y += -DABK_MANAGER_OFFICIAL_CERT=1
ifneq ($(KBUILD_EXTMOD),)
# External LKM builds do not run this tree's Kconfig, so expose the
# tristate to the preprocessor after inheriting CONFIG_KSU above.
ccflags-y += -DCONFIG_ABK_CONTROL=1
endif
$(info -- ABK manager package name: $(ABK_MANAGER_PACKAGE))
$(info -- ABK manager certificate size: $(ABK_MANAGER_CERT_SIZE))
$(info -- ABK manager certificate hash: $(ABK_MANAGER_CERT_SHA256))
endif

ccflags-y += -Wno-strict-prototypes -Wno-int-conversion -Wno-gcc-compat -Wno-missing-prototypes
ccflags-y += -Wno-declaration-after-statement -Wno-unused-function

# Keep a new line here!! Because someone may append config
