#ifndef __KSU_UAPI_FEATURE_H
#define __KSU_UAPI_FEATURE_H

enum ksu_feature_id {
    KSU_FEATURE_SU_COMPAT = 0,
    KSU_FEATURE_KERNEL_UMOUNT = 1,
    KSU_FEATURE_SULOG = 2,
    KSU_FEATURE_ADB_ROOT = 3,
    KSU_FEATURE_SELINUX_HIDE = 4,
    KSU_FEATURE_AVC_SPOOF = 5,
    /* Read-only runtime report for the core Hook dispatcher. */
    KSU_FEATURE_HOOK_STATUS = 6,
    KSU_FEATURE_WEBVIEW_ZYGOTE_UMOUNT = 7,
    /* Read-only GKI Seccomp hook diagnostics. */
    KSU_FEATURE_SECCOMP_HOOK_STATUS = 8,
    KSU_FEATURE_SECCOMP_HOOK_LAST_ERROR = 9,
    KSU_FEATURE_SECCOMP_HOOK_CALL_COUNT = 10,
    KSU_FEATURE_SECCOMP_HOOK_RELEASE_COUNT = 11,
    KSU_FEATURE_SECCOMP_HOOK_FAILURE_COUNT = 12,

    KSU_FEATURE_MAX
};

#define KSU_FEATURE_AVC_SPOOF_LEGACY 10003

/* KSU_FEATURE_HOOK_STATUS bit flags. */
#define KSU_HOOK_STATUS_MANAGER_READY (1ULL << 0)
#define KSU_HOOK_STATUS_SYSCALL_HANDLERS (1ULL << 1)
#define KSU_HOOK_STATUS_TRACEPOINT (1ULL << 2)
#define KSU_HOOK_STATUS_KRETPROBES (1ULL << 3)
#define KSU_HOOK_STATUS_LSM (1ULL << 4)

/* KSU_FEATURE_SECCOMP_HOOK_STATUS bit flags. */
#define KSU_SECCOMP_HOOK_STATUS_KERNEL_SUPPORTED (1ULL << 0)
#define KSU_SECCOMP_HOOK_STATUS_CONFIG_ENABLED (1ULL << 1)
#define KSU_SECCOMP_HOOK_STATUS_INITIALIZED (1ULL << 2)
#define KSU_SECCOMP_HOOK_STATUS_READY (1ULL << 3)
#define KSU_SECCOMP_HOOK_STATUS_RELEASE_PROBE_REQUIRED (1ULL << 4)
#define KSU_SECCOMP_HOOK_STATUS_RELEASE_PROBE_COMPLETE (1ULL << 5)
#define KSU_SECCOMP_HOOK_STATUS_RELEASE_PROBE_FALLBACK (1ULL << 6)
#define KSU_SECCOMP_HOOK_STATUS_RELEASE_USES_SIGLOCK (1ULL << 7)
#define KSU_SECCOMP_HOOK_STATUS_RUNTIME_VERIFIED (1ULL << 8)
#define KSU_SECCOMP_HOOK_STATUS_LAST_CALL_SUCCEEDED (1ULL << 9)
#define KSU_SECCOMP_HOOK_STATUS_LAST_CALL_FAILED (1ULL << 10)

#endif
